#!/usr/bin/env bash
# Phase 05 — HIGH SIDE. Work out exactly which images this cluster needs.
#
#   scripts/05-discover-images.sh
#
# Writes config/required-images.txt: the ModelCar weights plus every image the
# RUNNING cluster says llm-d will pull, read out of the LLMInferenceServiceConfig
# presets and the KServe storage config.
#
# This exists because the list is not knowable in advance. It is specific to the
# RHOAI z-stream installed here, and a hard-coded list goes stale on the next
# one. On the cluster this was built against, RHOAI reported Ready while all
# four llm-d component images were missing from the mirror — nothing pulls the
# inference scheduler, routing sidecar, KV-cache or storage initializer until
# the first LLMInferenceService is created, so the gap stays invisible until the
# moment you try to use it.
#
# Runs here rather than on the low side because only this host can reach the
# cluster. `scripts/remote.sh sync` carries the result to the low side, which is
# the host that can reach the internet.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_env

require_cmd oc jq
require_cluster_admin

OUT="${REPO_ROOT}/config/required-images.txt"

step "Phase 05 — discovering the images this cluster needs"

# --- what accelerators exist here ------------------------------------------
gpus="$(oc get nodes -o json | jq '[.items[].status.capacity["nvidia.com/gpu"] // "0" | tonumber] | add')"
ok "${gpus} NVIDIA GPU(s) in the cluster"

# --- presets and storage config --------------------------------------------
preset="$(oc get llminferenceserviceconfig -A -o json 2>/dev/null \
  | jq -r '[.. | .image? // empty] | unique[]' 2>/dev/null || true)"
si="$(oc get configmap inferenceservice-config -n "$KSERVE_NAMESPACE" \
  -o jsonpath='{.data.storageInitializer}' 2>/dev/null | jq -r '.image // empty' || true)"

declared="$(printf '%s\n%s\n' "$preset" "$si" | grep -E '^[a-z0-9.-]+\.[a-z]+/' | sort -u || true)"
[[ -n "$declared" ]] || die "found no images in the LLMInferenceServiceConfig presets.
     Either the llm-d stack is not installed, or KSERVE_NAMESPACE is wrong
     (currently '${KSERVE_NAMESPACE}'; RHOAI uses redhat-ods-applications)."

# Drop runtimes for accelerators this cluster does not have. They are declared
# by the presets regardless of hardware, and mirroring all of them costs tens of
# gigabytes for images that can never be scheduled here.
keep=""; skipped=""
while read -r img; do
  [[ -n "$img" ]] || continue
  if [[ "$img" =~ vllm-(rocm|gaudi|spyre) ]] && (( gpus > 0 )); then
    skipped+="  ${img}"$'\n'
  else
    keep+="${img}"$'\n'
  fi
done <<< "$declared"

# ---------------------------------------------------------------------------
{
  echo "# Generated by scripts/05-discover-images.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Cluster: $(oc whoami --show-server 2>/dev/null)"
  echo "#"
  echo "# Do not hand-edit — re-run the script. The digests are specific to the"
  echo "# RHOAI version installed on THIS cluster."
  echo
  echo "# --- model weights (ModelCar) ---"
  echo "$MODELCAR_QWEN25_05B"
  echo "$MODELCAR_QWEN3_4B"
  echo
  echo "# --- httpd base for the disconnected GPU kernel/CUDA repo ---"
  echo "$KERNEL_REPO_BASE_IMAGE"
  echo
  echo "# --- llm-d components declared by this cluster ---"
  printf '%s' "$keep"
} > "$OUT"

n="$(grep -cvE '^\s*#|^\s*$' "$OUT" || true)"
ok "wrote ${n} image(s) to config/required-images.txt"

if [[ -n "$skipped" ]]; then
  echo
  log "skipped (other accelerators, not present on this cluster):"
  printf '%s' "$skipped"
fi

echo
grep -vE '^\s*#|^\s*$' "$OUT" | sed 's/^/  /'

cat <<EOF

  Next, from your LAPTOP so the low side gets this list:

    scripts/remote.sh sync

EOF
