#!/usr/bin/env bash
# Phase 10 — LOW SIDE. Pull every required image down to disk.
#
#   scripts/10-mirror-images.sh
#
# Generates an ImageSetConfiguration from config/required-images.txt and runs
# oc-mirror in mirrorToDisk mode. Incremental: images already in the oc-mirror
# cache are skipped, so re-running after adding one image is cheap.
#
# WHY THIS DOES NOT USE THE RHOAI INSTALL PIPELINE
#
# The obvious move is to append to the disconnected RHOAI install's config/additional-images.txt and run
# `deploy-rhoai.sh 10`. Do not. That regenerates the FULL RHOAI
# ImageSetConfiguration, and its phase 20 then emits IDMS objects named
# idms-operator-0 / idms-generic-0. `oc apply` REPLACES objects of the same
# name — it does not merge — so if the regenerated set is narrower than what is
# already on the cluster, mirror rules other workloads depend on vanish. On the
# cluster this was built against, idms-operator-0 already existed and was in use
# by a MaaS deployment.
#
# A separate batch with its own workdir and its own registry namespace produces
# distinctly-named IDMS objects, so applying them only ever ADDS.
#
# It also avoids re-walking a ~300 GB operator catalog to add 8 GB of weights.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_env

require_cmd oc-mirror oc
require_vars LLMD_WORKDIR

LIST="${REPO_ROOT}/config/required-images.txt"
# Written INTO the workdir, not the repo: phase 15 rsyncs the workdir, so the
# config travels with the archive it describes and phase 18 pushes using exactly
# the config that produced it. A copy in the repo would not reach the high side.
ISC="${LLMD_WORKDIR}/imageset-config.yaml"

[[ -f "$LIST" ]] || die "no config/required-images.txt.

     It is produced on the HIGH side, which is the only host that can read the
     cluster, then carried here by \`scripts/remote.sh sync\`:

       high side:  ./deploy-llmd.sh 05
       laptop:     scripts/remote.sh sync"

step "Phase 10 — mirroring to disk"

# --- pull secret ------------------------------------------------------------
# oc-mirror reads auth from the containers runtime dir, not from ~/pull-secret.
AUTH_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/containers"
PULL_SECRET="${RH_PULL_SECRET_FILE:-${HOME}/pull-secret.json}"
if [[ -r "$PULL_SECRET" ]]; then
  run mkdir -p "$AUTH_DIR"
  run cp -f "$PULL_SECRET" "${AUTH_DIR}/auth.json"
  ok "pull secret staged for oc-mirror"
else
  warn "no pull secret at ${PULL_SECRET} — registry.redhat.io images will fail"
fi

# --- generate the ImageSetConfiguration ------------------------------------
run mkdir -p "$LLMD_WORKDIR"

if [[ "${DRY_RUN:-false}" != "true" ]]; then
  {
    echo "# Generated by scripts/10-mirror-images.sh — do not edit."
    echo "# Source of truth is config/required-images.txt."
    echo "apiVersion: mirror.openshift.io/v2alpha1"
    echo "kind: ImageSetConfiguration"
    echo "mirror:"
    echo "  additionalImages:"
    grep -vE '^\s*#|^\s*$' "$LIST" | sed 's/^/    - name: /'
  } > "$ISC"
  n="$(grep -c 'name:' "$ISC" || true)"
  ok "generated ${ISC} (${n} images)"
fi

# --- mirror -----------------------------------------------------------------
LOG="${LLMD_LOG_DIR}/llmd-mirror-$(date +%Y%m%d-%H%M%S).log"
step "Running oc-mirror (log: ${LOG})"
log "  first run downloads everything; later runs only fetch what changed"

if [[ "${DRY_RUN:-false}" == "true" ]]; then
  dim "would run: oc-mirror --v2 --config ${ISC} file://${LLMD_WORKDIR}"
  exit 0
fi

set +e
oc-mirror --v2 --config "$ISC" "file://${LLMD_WORKDIR}" 2>&1 | tee "$LOG"
rc=${PIPESTATUS[0]}
set -e

# oc-mirror exits non-zero for soft failures too, so judge by the artifact — the
# The rule: prove progress by measuring the thing being produced.
tar="$(ls -t "${LLMD_WORKDIR}"/*.tar 2>/dev/null | head -1 || true)"
if [[ -z "$tar" ]]; then
  err="$(ls -t "${LLMD_WORKDIR}"/working-dir/logs/mirroring_errors_*.txt 2>/dev/null | head -1 || true)"
  [[ -n "$err" ]] && { echo; warn "errors:"; sed 's/^/    /' "$err" | head -10; }
  die "oc-mirror produced no archive (exit ${rc}) — see ${LOG}"
fi

ok "archive: ${tar} ($(du -h "$tar" | cut -f1))"
(( rc == 0 )) || warn "oc-mirror exited ${rc} but produced an archive — check ${LOG} before continuing"

echo
ok "phase 10 complete — next: ./deploy-llmd.sh 15"
