#!/usr/bin/env bash
# Phase 18 — HIGH SIDE. Push into Quay and wire up the mirror rules.
#
#   scripts/18-push-images.sh
#
# Three things, and the last two are where people come unstuck:
#
#   1. oc-mirror diskToMirror into its OWN registry namespace
#   2. rename the generated IDMS/ITMS before applying them
#   3. apply, then wait for the MachineConfig rollout to actually land
#
# On (2): oc-mirror always names its output idms-generic-0 / itms-generic-0.
# `oc apply` REPLACES an object of the same name rather than merging, so a
# second oc-mirror batch — from any project — would silently overwrite the
# first one's mirror rules. Renaming to idms-llmd-* keeps this project's rules
# independent, matching the idms-maas-* convention already used on the cluster.
#
# On (3): the MCO takes a moment to notice a new IDMS. Polling immediately gets
# a "settled" answer describing the PREVIOUS state, so this waits first and then
# proves the rule reached a node's registries.conf rather than trusting the
# MachineConfigPool condition.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_env

require_cmd oc-mirror oc jq podman
require_cluster_admin
require_vars MIRROR_REGISTRY LLMD_WORKDIR LLMD_MIRROR_NAMESPACE

ISC="${LLMD_WORKDIR}/imageset-config.yaml"
CR="${LLMD_WORKDIR}/working-dir/cluster-resources"

[[ -f "$ISC" ]] || die "no ${ISC}

     It is generated by phase 10 on the LOW side and carried here by phase 15,
     alongside the archive it describes. Run those two first:
       low side: ./deploy-llmd.sh low"
ls "${LLMD_WORKDIR}"/*.tar >/dev/null 2>&1 || die "no archive in ${LLMD_WORKDIR} — run phase 15 on the low side"

step "Phase 18 — pushing to ${MIRROR_REGISTRY}/${LLMD_MIRROR_NAMESPACE}"

# --- registry disk ----------------------------------------------------------
# Checked before starting because a full Quay volume fails as 502 Bad Gateway
# on every blob upload, with the real cause (ENOSPC) visible only inside the
# quay-app container log.
qs="${MIRROR_REGISTRY_QUAY_STORAGE:-}"
if [[ -n "$qs" && -d "$qs" ]]; then
  free_gib=$(( $(df -Pk "$qs" | awk 'NR==2{print $4}') / 1048576 ))
  need_gib=$(( $(du -sk "${LLMD_WORKDIR}" | cut -f1) / 1048576 * 2 ))
  if (( free_gib >= need_gib )); then
    ok "registry storage: ${free_gib} GiB free (want ~${need_gib} GiB)"
  else
    die "registry storage has ${free_gib} GiB free but this push needs ~${need_gib} GiB.

     Pushes fail as '502 Bad Gateway', not as a disk error. Reclaim abandoned
     partial uploads — these are never-committed blobs, safe to delete when no
     push is running:
       du -sh ${qs}/uploads
       find ${qs}/uploads -type f -mmin +360 -delete
     Or grow the volume:
       aws ec2 modify-volume --volume-id <id> --size <GB> && sudo xfs_growfs ${qs}"
  fi
fi

# --- auth -------------------------------------------------------------------
AUTH_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/containers"
run mkdir -p "$AUTH_DIR"
if [[ "${DRY_RUN:-false}" != "true" ]]; then
  podman login --authfile "${AUTH_DIR}/auth.json" \
    -u "$MIRROR_REGISTRY_USER" -p "$MIRROR_REGISTRY_PASSWORD" "$MIRROR_REGISTRY" >/dev/null 2>&1 \
    || die "cannot log in to ${MIRROR_REGISTRY} — check MIRROR_REGISTRY_USER/PASSWORD in ${RHOAI_REPO_ENV}"
  ok "authenticated to the mirror registry"
fi

# --- is there anything to do? ----------------------------------------------
#
# oc-mirror's archives are INCREMENTAL against the low side's own history, not
# against the destination registry. Re-run phase 10 after a successful push and
# it produces a near-empty delta archive, because as far as that host is
# concerned the work is done. Feeding that back to diskToMirror fails with
#   manifest unknown ... localhost:55000
# which looks alarming and means only "there was nothing new in the box".
#
# So: check the registry first. If every required image is already there, this
# phase has nothing to push and should say so rather than fail.
LIST="${REPO_ROOT}/config/required-images.txt"
need_push=true
if [[ -f "$LIST" ]]; then
  load_mirror_rules
  missing=0 checked=0
  while read -r img; do
    [[ -n "$img" ]] || continue
    checked=$(( checked + 1 ))
    mirror_has_image "$img" || missing=$(( missing + 1 ))
  done < <(grep -vE '^\s*#|^\s*$' "$LIST")
  if (( checked > 0 && missing == 0 )); then
    need_push=false
    ok "all ${checked} required image(s) are already in the registry — skipping the push"
  else
    log "  ${missing} of ${checked} image(s) still to push"
  fi
fi

# --- push -------------------------------------------------------------------
# --config is mandatory in BOTH directions and --from needs the file:// scheme.
# Omit either and oc-mirror prints its full usage and
#   [Executor] use the --config flag it is mandatory
LOG="${LLMD_LOG_DIR}/llmd-push-$(date +%Y%m%d-%H%M%S).log"
if [[ "$need_push" != "true" ]]; then
  step "Skipping oc-mirror — registry already has everything"
else
step "Running oc-mirror diskToMirror (log: ${LOG})"

if [[ "${DRY_RUN:-false}" == "true" ]]; then
  dim "would run: oc-mirror --v2 --config ${ISC} --from file://${LLMD_WORKDIR} docker://${MIRROR_REGISTRY}/${LLMD_MIRROR_NAMESPACE}"
else
  set +e
  oc-mirror --v2 --config "$ISC" --from "file://${LLMD_WORKDIR}" \
    "docker://${MIRROR_REGISTRY}/${LLMD_MIRROR_NAMESPACE}" 2>&1 | tee "$LOG"
  rc=${PIPESTATUS[0]}
  set -e

  if (( rc != 0 )); then
    err="$(ls -t "${LLMD_WORKDIR}"/working-dir/logs/mirroring_errors_*.txt 2>/dev/null | head -1 || true)"
    if [[ -n "$err" ]]; then
      echo; warn "oc-mirror reported errors:"; sed 's/^/    /' "$err" | head -6
      if grep -qi "502 Bad Gateway" "$err"; then
        die "502 from the registry means Quay's blob volume is full. See the disk
     advice at the top of this script."
      fi
      if grep -qi "manifest unknown.*localhost:55000" "$err"; then
        die "oc-mirror cannot read the content out of its own cache.

     Two causes, in order of likelihood:

     1. The archive is an INCREMENTAL delta with nothing in it, because phase 10
        was re-run on the low side after a successful push. Check whether the
        images are in fact already present — if they are, there is nothing to do:
          ./deploy-llmd.sh 20
        To force a full archive, clear the low side's mirror state and re-run:
          rm -rf ${LLMD_WORKDIR}/working-dir && ./deploy-llmd.sh 10

     2. The archive is corrupt from an rsync --append transfer. Re-run phase 15,
        which verifies a prefix hash and refuses a bad copy."
      fi
    fi
    die "oc-mirror failed (exit ${rc}) — see ${LOG}"
  fi
  ok "images pushed"
fi
fi

# --- IDMS / ITMS ------------------------------------------------------------
step "Applying mirror rules (renamed so they cannot clobber other batches)"

[[ -d "$CR" || "${DRY_RUN:-false}" == "true" ]] || die "no cluster-resources in ${CR}"

# MERGE, never replace.
#
# oc-mirror regenerates these files from whatever was in THIS archive. On an
# incremental run that is a subset, so a plain `oc apply` — which replaces the
# whole object — silently DELETES the mirror rules for everything that was
# pushed previously. That is not hypothetical: it happened here, and the
# symptom was the ModelCar images suddenly reporting "no mirror rule" hours
# after they had been successfully mirrored.
#
# So the rules are unioned with whatever the object already holds, keyed by
# source. Rules only ever accumulate.
merge_mirror_set() {
  local kind="$1" file="$2" name="$3" field="$4"

  local gen
  gen="$(oc create -f "$file" --dry-run=client -o json 2>/dev/null)" || return 1
  # A multi-document file comes back as a List.
  local new
  new="$(printf '%s' "$gen" | jq -c --arg f "$field" '
    if .kind == "List" then [.items[] | .spec[$f][]?] else [.spec[$f][]?] end')"

  local existing='[]'
  if oc get "$kind" "$name" >/dev/null 2>&1; then
    existing="$(oc get "$kind" "$name" -o json | jq -c --arg f "$field" '[.spec[$f][]?]')"
  fi

  local merged
  merged="$(jq -n --argjson a "$existing" --argjson b "$new" '
    ($a + $b)
    | group_by(.source)
    | map({source: .[0].source, mirrors: (map(.mirrors[]?) | unique)})
    | sort_by(.source)')"

  local before after
  before="$(printf '%s' "$existing" | jq 'length')"
  after="$(printf '%s'  "$merged"   | jq 'length')"

  local api kindName
  case "$kind" in
    idms) api="config.openshift.io/v1"; kindName="ImageDigestMirrorSet" ;;
    itms) api="config.openshift.io/v1"; kindName="ImageTagMirrorSet" ;;
  esac

  jq -n --arg api "$api" --arg k "$kindName" --arg n "$name" \
        --arg f "$field" --argjson m "$merged" '
    {apiVersion:$api, kind:$k,
     metadata:{name:$n, annotations:{"llmd.criab/owner":"disconnected-llm-d"}},
     spec:{ ($f): $m }}' | oc apply -f - >/dev/null

  ok "${kind}/${name}: ${before} -> ${after} rule(s) (merged, never replaced)"
}

applied=0
for kind in idms itms; do
  f="${CR}/${kind}-oc-mirror.yaml"
  [[ -f "$f" ]] || continue
  new="${kind}-llmd-generic-0"
  case "$kind" in
    idms) field=imageDigestMirrors ;;
    itms) field=imageTagMirrors ;;
  esac
  if [[ "${DRY_RUN:-false}" == "true" ]]; then
    dim "would merge ${f} into ${kind}/${new}"
  else
    merge_mirror_set "$kind" "$f" "$new" "$field" || { warn "could not merge ${f}"; continue; }
    applied=$(( applied + 1 ))
  fi
done

(( applied > 0 )) || warn "no IDMS/ITMS files were generated — nothing to apply"

# --- rollout ----------------------------------------------------------------
[[ "${DRY_RUN:-false}" == "true" ]] && { ok "phase 18 complete (dry run)"; exit 0; }

step "Waiting for the MachineConfig rollout (nodes may reboot)"
# Give the MCO time to notice. Without this the first poll answers about the
# state BEFORE the change and reports success immediately.
sleep 45

mcp_settled() {
  [[ "$(oc get mcp -o json | jq '[.items[] |
        select(((.status.conditions[]|select(.type=="Updated")|.status) != "True")
            or ((.status.conditions[]|select(.type=="Degraded")|.status) == "True"))] | length')" == "0" ]]
}
wait_for "all MachineConfigPools updated" "${WAIT_TIMEOUT:-1800}" mcp_settled

# Prove it landed rather than trusting the condition.
node="$(oc get nodes -o jsonpath='{.items[0].metadata.name}')"
if oc debug "node/${node}" -q -- chroot /host grep -q "${LLMD_MIRROR_NAMESPACE}" /etc/containers/registries.conf 2>/dev/null; then
  ok "mirror rules are live in registries.conf on ${node}"
else
  warn "could not confirm the rule in registries.conf on ${node} — check manually:"
  warn "  oc debug node/${node} -- chroot /host grep -A3 redhat-ai-services /etc/containers/registries.conf"
fi

echo
ok "phase 18 complete — next: ./deploy-llmd.sh 20"
