#!/usr/bin/env bash
# Run this repo on the lab hosts from your laptop.
#
#   scripts/remote.sh sync              # copy the repo to BOTH hosts
#   scripts/remote.sh ssh low|high      # interactive shell
#   scripts/remote.sh run high -- './deploy-llmd.sh 40'
#
# Host addresses and the SSH key come from the disconnected RHOAI install's config/criab.env, so there is
# exactly one place to keep them. `sync` also pulls config/required-images.txt
# back from the high side, because that file is produced there (it needs the
# cluster) and consumed on the low side (which needs the internet).

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_env

# LLMD_LOW_HOST / LLMD_HIGH_HOST win over the RHOAI install's values.
#
# the disconnected RHOAI install's config/criab.env sets the host addresses twice — a ${VAR:-default}
# line near the top and a literal assignment at the bottom — so the literal one
# always wins, and a laptop whose RHOAI-install checkout points at a different lab will
# happily sync this repo to the WRONG cluster. Setting these two in
# config/llmd.env is the safe way to pin an environment.
LOW_SIDE_HOST="${LLMD_LOW_HOST:-${LOW_SIDE_HOST:-}}"
HIGH_SIDE_HOST="${LLMD_HIGH_HOST:-${HIGH_SIDE_HOST:-}}"

require_vars LOW_SIDE_HOST HIGH_SIDE_HOST
LOW_SIDE_USER="${LOW_SIDE_USER:-lab-user}"
HIGH_SIDE_USER="${HIGH_SIDE_USER:-lab-user}"

step "Targets: low=${LOW_SIDE_HOST}  high=${HIGH_SIDE_HOST}"
REMOTE_DIR="${LLMD_REMOTE_DIR:-/home/${LOW_SIDE_USER}/disconnected-llm-d}"

SSH_CONFIG="${REPO_ROOT}/.ssh-config"

# A generated config, not inline -o flags. `-i` does not propagate across `-J`,
# so a hand-rolled ProxyJump silently falls back to password auth and hangs.
write_ssh_config() {
  local ident=""
  [[ -n "${LAB_SSH_KEY:-}" ]] && ident="  IdentityFile ${LAB_SSH_KEY}"
  cat > "$SSH_CONFIG" <<EOF
# Generated by scripts/remote.sh — overwritten each run.
Host llmd-low
  HostName ${LOW_SIDE_HOST}
  User ${LOW_SIDE_USER}
${ident}
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR

Host llmd-high
  HostName ${HIGH_SIDE_HOST}
  User ${HIGH_SIDE_USER}
${ident}
  ProxyJump llmd-low
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
EOF
  chmod 600 "$SSH_CONFIG"
}

write_ssh_config
# config/required-images.txt is EXCLUDED from the mirrored sync on purpose.
# It is generated on the high side by phase 05, and with --delete a plain sync
# from a laptop that does not have it yet would delete it remotely — throwing
# away the very thing the next step needs. It is moved explicitly below instead.
RS=(-az --delete -e "ssh -F ${SSH_CONFIG}"
    --exclude .git --exclude .ssh-config
    --exclude 'config/llmd.env' --exclude 'config/required-images.txt'
    --exclude 'working/' --exclude '*.log')

case "${1:-}" in
  sync)
    for h in llmd-low llmd-high; do
      step "Syncing to ${h}:${REMOTE_DIR}"
      rsync "${RS[@]}" "${REPO_ROOT}/" "${h}:${REMOTE_DIR}/"
      ok "$h"
    done
    # Pull the discovered image list back so the low side can mirror it. It is
    # written on the high side because only that host can read the cluster.
    if ssh -F "$SSH_CONFIG" llmd-high "test -f ${REMOTE_DIR}/config/required-images.txt" 2>/dev/null; then
      rsync -a -e "ssh -F ${SSH_CONFIG}" \
        "llmd-high:${REMOTE_DIR}/config/required-images.txt" "${REPO_ROOT}/config/" \
        && ok "pulled config/required-images.txt from the high side"
      rsync -a -e "ssh -F ${SSH_CONFIG}" \
        "${REPO_ROOT}/config/required-images.txt" "llmd-low:${REMOTE_DIR}/config/" \
        && ok "pushed it to the low side"
    fi
    ;;
  ssh)
    case "${2:-}" in low) t=llmd-low ;; high) t=llmd-high ;; *) die "usage: $0 ssh <low|high>" ;; esac
    exec ssh -F "$SSH_CONFIG" -t "$t" "cd ${REMOTE_DIR} 2>/dev/null; exec \$SHELL -l"
    ;;
  run)
    case "${2:-}" in low) t=llmd-low ;; high) t=llmd-high ;; *) die "usage: $0 run <low|high> -- <cmd>" ;; esac
    shift 2; [[ "${1:-}" == "--" ]] && shift || die "put the command after --"
    exec ssh -F "$SSH_CONFIG" -t "$t" "cd ${REMOTE_DIR} && $*"
    ;;
  *)
    die "usage: $0 <sync|ssh|run> ..."
    ;;
esac
